check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -99,13 +99,50 @@ jobs:
       - name: Run R CMD build (non-windows)
         if: matrix.os != 'windows-latest'
         run: |
-          _R_CHECK_CRAN_INCOMING=false R CMD build ./changeforest-r --no-manual
+          R CMD build ./changeforest-r --no-manual
+
+      - name: Run R CMD check (non-windows)
+        if: matrix.os != 'windows-latest'
+        run: |
+          _R_CHECK_CRAN_INCOMING_=false R CMD check --as-cran --no-vignettes --no-manual changeforest_*.tar.gz
+
+      - name: Check log files for warnings (non-windows)
+        if: matrix.os != 'windows-latest'
+        run: |
+          CHECK_LOG_FILE=changeforest-r.Rcheck/00check.log
+          CHECK_INSTALL_FILE=changeforest-r.Rcheck/00install.out
+          if ! [[ -f "$CHECK_LOG_FILE" ]]; then
+            echo "Log-file not found."
+            exit 1
+          fi
+          if cat $CHECK_LOG_FILE | grep -q "ERROR"; then
+            cat $CHECK_INSTALL_FILE
+            cat $CHECK_LOG_FILE
+            exit 1
+          fi
+          if cat $CHECK_LOG_FILE | grep -q "WARNING"; then
+            echo "Found warnings, treated as errors."
+            cat $CHECK_LOG_FILE
+            exit 1
+          fi
+        # e: pipefail
+        # x: print commands
+        # u: unset variables are errors
+        # l: as login script
+        shell: bash -lxu {0}
 
       - name: Run R CMD build (windows)
         if: matrix.os == 'windows-latest'
         run: |
-          R.exe CMD build ./changeforest-r --no-manual     
-      
+          R.exe CMD build ./changeforest-r --no-manual    
+
+      - name: Run R CMD check (windows)
+        if: matrix.os == 'windows-latest'
+        run: |
+          R.exe CMD check --as-cran --no-vignettes --no-manual changeforest_*.tar.gz
+
+      - name: Rename tarball
+        run: for x in changeforest_*.tar.gz; do mv $x ${x%.tar.gz}-${{ matrix.os }}.tar.gz; done
       - uses: actions/upload-artifact@v2
         with:
           name: r-builds
