Don't allow warnings.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -93,4 +93,8 @@ jobs:
       - name: Run R CMD check
         run: |
           _R_CHECK_CRAN_INCOMING_=false R CMD check --as-cran --no-vignettes --no-manual ./hdcd-r
+          if cat hdcd-r/hdcdr.Rcheck/00check.log | grep -q "WARNING"; then
+            echo "Found warnings, treated as errors."
+            exit 1
+          fi
         shell: bash -l {0}
